# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/prospector
    rev: 1.3.1 # The version of Prospector to use, at least 1.1.7
    hooks:
    -   id: prospector
        additional_dependencies: ['pyroma>=2.4']
-   repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
