---
author: "https://github.com/fair-software"
branding:
  color: purple
  icon: check
description: "Analyze compliance with fair-software.eu recommendations"
name: fair-software
runs:
  image: Dockerfile
  using: docker
