---
author: "https://github.com/fair-software"
branding:
  color: purple
  icon: check
description: "Analyze compliance with fair-software.eu recommendations"
name: fair-software
  REPO_URL:
    description: 'URL of the GitHub repository for which to run the analysis'
    required: false
runs:
  image: Dockerfile
  using: docker
