---
author: "https://github.com/fair-software"
branding:
  color: purple
  icon: check
description: "Analyze compliance with fair-software.eu recommendations"
name: fair-software
inputs:
  REPOSITORY:
    description: URL of the repository being inspected
    required: true
runs:
  image: Dockerfile
  using: docker
