name: dockertest

# When a new release is published onn GitHub, this workflow check if the Docker
# image can successfully be built from the Dockerfile

on:
  release:
    types:
      - published

jobs:
  docker:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out a copy of the repository

      - name: Build image
        run: docker build . --file Dockerfile
