name: RunFAIRSECO

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  RunTortellini:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: tortellini-tools/action@v3
            - uses: actions/upload-artifact@v3
              with:
                  name: tortellini-result
                  path: .tortellini/out
  
  RunSBOM:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: anchore/sbom-action@v0
              with:
                  artifact-name: SBOM.spdx # Output is in JSON format
  
  RunFAIRSECO:
        needs: [RunTortellini, RunSBOM]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/checkout@v3
              with:
                repository: QDUNI/FairSECO
                path: FAIRSECO_Assets
                ref: 'dev'
            - uses: QDUNI/FairSECO@dev
              with:
                  myToken: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/upload-artifact@v3
              with:
                  name: FAIRSECO Result
                  path: .FAIRSECO/
